### PR TITLE
Fix texture mirroring

### PR DESCRIPTION
**Pull request by edbefee3-3888-462a-9411-741b7e9eb54e**
Fixes texture mirroring, compacts TexCoordMatrix, and adds '.' to the _bckPaths

### CODE REVIEW

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Sorry for the mess btw, i'm new to creating PRs

**Comment by niacdoial** [comment]
I'm… honestly impressed by the work you did. (including understanding code I wrote 4 years ago, that must not have been easy lol)
Nice work, about all of this!
The only thing I think could benefit from more tweaking? The part where you re-wrote a description : Maybe the entire string can benefit from being "If you choose to import animations, you can choose to chain them or put them in individual actions". Your correction is still better than the original "if yes" description.
Other than that, it's ready to be merged!

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Sure, I'll just change all the descriptions and names to have capitalization, and maybe tweak a few of them to be a bit clearer

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
and that code definitely is a mess to read

**Comment by niacdoial** [comment]
alright, looks good to me!
should I merge it now, or are there other changes you want to put in this?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
I'd say merge

**Comment by niacdoial** [comment]
merged!

**Pull request merged**
