### PR TITLE
a bit of stuff at the beggining of common.py

### PR DESCRIPTION
**Pull request by edbefee3-3888-462a-9411-741b7e9eb54e**

### CODE REVIEW

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
the Bmodel.py thing is a git bug

**Comment by niacdoial** [comment]
nah, it's not a bug, it's that your code editor changed the file from CRLF to LF (before, it used "\r\n" to switch lines, and now it uses just "\n". Honestly, I needed to do this at some point, so might as well do it now)

Is it ready to be pulled, or do you think you want to add something else to this request first?

**Comment by niacdoial** [comment]
…huh. there are also a few unrelated lines that seem to have sneaked their way in from local code.
I'll deal with them when merging.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
for this PR, i think it can be merged, but i might do some more refactoring

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
next step is making file filtering work

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
done, the problem was an `=` instead a `:`

**Pull request merged**
